server:
  port: 8088

# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wiki?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: wiki
    password: 123

# 配置mybatis所有Mapper.xml所在的路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
# 开启日志
logging:
  level:
    com.objectsky.wiki: trace

